[package]
name = "esp32-dht11-rs"
version = "0.1.4"
authors = ["wendell <3461739@qq.com>"]
edition = "2021"
description = "A Rust crate that reads temperature and humidity data from the DHT11 sensors for esp32 series."
homepage = "https://github.com/wendell1002/esp32-dht11-rs"
documentation = "https://docs.rs/esp32-dht11-rs"
readme = "README.md"
keywords = ["embedded", "no-std", "dht11"]
license = "MIT"
repository = "https://github.com/wendell1002/esp32-dht11-rs"

[features]
default = ["esp32c3"]
esp32 = ["esp-hal/esp32"]
esp32c2 = ["esp-hal/esp32c2"]
esp32c3 = ["esp-hal/esp32c3"]
esp32c6 = ["esp-hal/esp32c6"]
esp32h2 = ["esp-hal/esp32h2"]
esp32s2 = ["esp-hal/esp32s2"]
esp32s3 = ["esp-hal/esp32s3"]

[dependencies]
embedded-hal = "1.0.0"
esp-hal = { version = "=1.1.0", default-features = false, features = ["unstable"] }

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
debug = 2
debug-assertions = false
overflow-checks = false
incremental = false
